db.financialTransactions.remove();
db.financialTransactions.insert({ buyer: 'SHAW', seller: 'PUIG', transaction: { type : 'mlb_draft_cash', value : 8, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'MAD', transaction: { type : 'mlb_draft_cash', value : 5, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'LAZ', transaction: { type : 'mlb_draft_cash', value : 8,  year: 2014 }});
db.financialTransactions.insert({ buyer: 'HIV+', seller: 'SHAW', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'DBAG', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'MAD', transaction: { type: 'mlb_draft_cash', value: 7, year: 2014 }});
db.financialTransactions.insert({ buyer: 'DBAG', seller: 'PUIG', transaction: { type: 'fa_auction_cash', value: 1, year: 2014 }});
db.financialTransactions.insert({ buyer: 'LAZ', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 1, year: 2014 }});
db.financialTransactions.insert({ buyer: 'CHOB', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'CHOB', seller: 'PUIG', transaction: { type: 'fa_auction_cash', value: 99, year: 2014 }});
db.financialTransactions.insert({ buyer: 'CHOB', seller: 'PUIG', transaction: { type: 'milb_draft_swap_rights', round: 1, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SIDO', seller: 'GOB', transaction: { type: 'mlb_draft_cash', value: 6, year: 2014 }});
db.financialTransactions.insert({ buyer: 'GRAN', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 10, year: 2014 }});
db.financialTransactions.insert({ buyer: 'MAD', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 13, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'SHAW', transaction: { type: 'mlb_draft_cash', value: 8, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SHAW', seller: 'GLRY', transaction: { type: 'mlb_draft_cash', value: 5, year: 2014 }});
db.financialTransactions.insert({ buyer: 'HIV+', seller: 'PUIG', transaction: { type: 'milb_draft_swap_rights', round: 4, year: 2014 }});
db.financialTransactions.insert({ buyer: 'GLRY', seller: 'GOB', transaction: { type: 'mlb_draft_cash', value: 2, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'GRAN', transaction: { type: 'mlb_draft_cash', value: 7, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SHAW', seller: 'GRAN', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SHAW', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SHAW', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 3, year: 2015 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'MAD', transaction: { type: 'mlb_draft_cash', value: 5, year: 2014 }});
db.financialTransactions.insert({ buyer: 'GLRY', seller: 'GOB', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SHAW', seller: 'GLRY', transaction: { type: 'mlb_draft_cash', value: 5, year: 2014 }});
db.financialTransactions.insert({ buyer: 'JEFF', seller: 'MAD', transaction: { type: 'mlb_draft_cash', value: 5, year: 2014 }});
db.financialTransactions.insert({ buyer: 'PUIG', seller: 'JEFF', transaction: { type: 'mlb_draft_cash', value: 5, year: 2014 }});
db.financialTransactions.insert({ buyer: 'SIDO', seller: 'PUIG', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'CHOB', seller: 'GOB', transaction: { type: 'milb_draft_swap_rights', round: 3, year: 2014 }});
db.financialTransactions.insert({ buyer: 'JEFF', seller: 'CHOB', transaction: { type: 'mlb_draft_cash', value: 6, year: 2014 }});
db.financialTransactions.insert({ buyer: 'MAD', seller: 'CHOB', transaction: { type: 'mlb_draft_cash', value: 3, year: 2014 }});
