db.cash.insert({ team : "GOB",  type : "MLB", value : 260, year: 2015 });
db.cash.insert({ team : "GRAN", type : "MLB", value : 260, year: 2015 });
db.cash.insert({ team : "JEFF", year: 2015, type : "MLB", value : 260 });
db.cash.insert({ team : "GLRY", year: 2015, type : "MLB", value : 260 });
db.cash.insert({ team : "SIDO", year: 2015, type : "MLB", value : 260 });
db.cash.insert({ team : "DBAG", year: 2015, type : "MLB", value : 260 });
db.cash.insert({ team : "CHOB", type : "MLB", value : 260, year: 2015 });
db.cash.insert({ team : "HIV+", year: 2015, type : "MLB", value : 260 });
db.cash.insert({ team : "MAD",  type : "MLB", value : 260, year: 2015 });
db.cash.insert({ team : "LAZ",  year: 2015, type : "MLB", value : 260 });
db.cash.insert({ team : "PUIG", year : 2015, type : "MLB", value : 257 });
db.cash.insert({ team : "SHAW", type : "MLB", value : 263, year : 2015 });

db.cash.insert({ team : "GOB",  type : "MLB", value : 260, year : 2016 });
db.cash.insert({ team : "GRAN", type : "MLB", value : 260, year : 2016 });
db.cash.insert({ team : "SHAW", type : "MLB", value : 260, year : 2016 });
db.cash.insert({ team : "JEFF", year : 2016, type : "MLB", value : 260 });
db.cash.insert({ team : "GLRY", year : 2016, type : "MLB", value : 260 });
db.cash.insert({ team : "SIDO", year : 2016, type : "MLB", value : 260 });
db.cash.insert({ team : "DBAG", year : 2016, type : "MLB", value : 260 });
db.cash.insert({ team : "CHOB", type : "MLB", value : 260, year : 2016 });
db.cash.insert({ team : "HIV+", year : 2016, type : "MLB", value : 260 });
db.cash.insert({ team : "PUIG", year : 2016, type : "MLB", value : 260 });
db.cash.insert({ team : "MAD",  type : "MLB", value : 260, year : 2016 });
db.cash.insert({ team : "LAZ",  year : 2016, type : "MLB", value : 260 });

db.cash.insert({ team : "GOB",  type : "MLB", value : 260, year : 2017 });
db.cash.insert({ team : "GRAN", type : "MLB", value : 260, year : 2017 });
db.cash.insert({ team : "SHAW", type : "MLB", value : 260, year : 2017 });
db.cash.insert({ team : "JEFF", year : 2017, type : "MLB", value : 260 });
db.cash.insert({ team : "GLRY", year : 2017, type : "MLB", value : 260 });
db.cash.insert({ team : "SIDO", year : 2017, type : "MLB", value : 260 });
db.cash.insert({ team : "DBAG", year : 2017, type : "MLB", value : 260 });
db.cash.insert({ team : "CHOB", type : "MLB", value : 260, year : 2017 });
db.cash.insert({ team : "HIV+", year : 2017, type : "MLB", value : 260 });
db.cash.insert({ team : "PUIG", year : 2017, type : "MLB", value : 260 });
db.cash.insert({ team : "MAD",  type : "MLB", value : 260, year : 2017 });
db.cash.insert({ team : "LAZ",  year : 2017, type : "MLB", value : 260 });

db.cash.insert({ team : "GOB",  type : "MLB", value : 260, year: 2018 });
db.cash.insert({ team : "GRAN", type : "MLB", value : 260, year: 2018 });
db.cash.insert({ team : "SHAW", type : "MLB", value : 260, year: 2018 });
db.cash.insert({ team : "JEFF", year: 2018, type : "MLB", value : 260 });
db.cash.insert({ team : "GLRY", year: 2018, type : "MLB", value : 260 });
db.cash.insert({ team : "SIDO", year: 2018, type : "MLB", value : 260 });
db.cash.insert({ team : "DBAG", year: 2018, type : "MLB", value : 260 });
db.cash.insert({ team : "CHOB", type : "MLB", value : 260, year: 2018 });
db.cash.insert({ team : "HIV+", year: 2018, type : "MLB", value : 260 });
db.cash.insert({ team : "PUIG", year: 2018, type : "MLB", value : 260 });
db.cash.insert({ team : "MAD",  type : "MLB", value : 260, year: 2018 });
db.cash.insert({ team : "LAZ",  year: 2018, type : "MLB", value : 260 });

db.cash.insert({ team : "GOB",  type : "FA", value : 100, year: 2015 });
db.cash.insert({ team : "GRAN", type : "FA", value : 100, year: 2015 });
db.cash.insert({ team : "JEFF", year: 2015, type : "FA", value : 100 });
db.cash.insert({ team : "GLRY", year: 2015, type : "FA", value : 100 });
db.cash.insert({ team : "SIDO", year: 2015, type : "FA", value : 100 });
db.cash.insert({ team : "DBAG", year: 2015, type : "FA", value : 100 });
db.cash.insert({ team : "CHOB", type : "FA", value : 100, year: 2015 });
db.cash.insert({ team : "HIV+", year: 2015, type : "FA", value : 100 });
db.cash.insert({ team : "MAD",  type : "FA", value : 100, year: 2015 });
db.cash.insert({ team : "LAZ",  year: 2015, type : "FA", value : 100 });
db.cash.insert({ team : "PUIG", year : 2015, type : "FA", value : 100 });
db.cash.insert({ team : "SHAW", type : "FA", value : 100, year : 2015 });

db.cash.insert({ team : "GOB",  type : "FA", value : 100, year : 2016 });
db.cash.insert({ team : "GRAN", type : "FA", value : 100, year : 2016 });
db.cash.insert({ team : "SHAW", type : "FA", value : 100, year : 2016 });
db.cash.insert({ team : "JEFF", year : 2016, type : "FA", value : 100 });
db.cash.insert({ team : "GLRY", year : 2016, type : "FA", value : 100 });
db.cash.insert({ team : "SIDO", year : 2016, type : "FA", value : 100 });
db.cash.insert({ team : "DBAG", year : 2016, type : "FA", value : 100 });
db.cash.insert({ team : "CHOB", type : "FA", value : 100, year : 2016 });
db.cash.insert({ team : "HIV+", year : 2016, type : "FA", value : 100 });
db.cash.insert({ team : "PUIG", year : 2016, type : "FA", value : 100 });
db.cash.insert({ team : "MAD",  type : "FA", value : 100, year : 2016 });
db.cash.insert({ team : "LAZ",  year : 2016, type : "FA", value : 100 });

db.cash.insert({ team : "GOB",  type : "FA", value : 100, year : 2017 });
db.cash.insert({ team : "GRAN", type : "FA", value : 100, year : 2017 });
db.cash.insert({ team : "SHAW", type : "FA", value : 100, year : 2017 });
db.cash.insert({ team : "JEFF", year : 2017, type : "FA", value : 100 });
db.cash.insert({ team : "GLRY", year : 2017, type : "FA", value : 100 });
db.cash.insert({ team : "SIDO", year : 2017, type : "FA", value : 100 });
db.cash.insert({ team : "DBAG", year : 2017, type : "FA", value : 100 });
db.cash.insert({ team : "CHOB", type : "FA", value : 100, year : 2017 });
db.cash.insert({ team : "HIV+", year : 2017, type : "FA", value : 100 });
db.cash.insert({ team : "PUIG", year : 2017, type : "FA", value : 100 });
db.cash.insert({ team : "MAD",  type : "FA", value : 100, year : 2017 });
db.cash.insert({ team : "LAZ",  year : 2017, type : "FA", value : 100 });

db.cash.insert({ team : "GOB",  type : "FA", value : 100, year: 2018 });
db.cash.insert({ team : "GRAN", type : "FA", value : 100, year: 2018 });
db.cash.insert({ team : "SHAW", type : "FA", value : 100, year: 2018 });
db.cash.insert({ team : "JEFF", year: 2018, type : "FA", value : 100 });
db.cash.insert({ team : "GLRY", year: 2018, type : "FA", value : 100 });
db.cash.insert({ team : "SIDO", year: 2018, type : "FA", value : 100 });
db.cash.insert({ team : "DBAG", year: 2018, type : "FA", value : 100 });
db.cash.insert({ team : "CHOB", type : "FA", value : 100, year: 2018 });
db.cash.insert({ team : "HIV+", year: 2018, type : "FA", value : 100 });
db.cash.insert({ team : "PUIG", year: 2018, type : "FA", value : 100 });
db.cash.insert({ team : "MAD",  type : "FA", value : 100, year: 2018 });
db.cash.insert({ team : "LAZ",  year: 2018, type : "FA", value : 100 });