db.teams.insert({team:'GOB', owner:'Ari Golub', fullName:'I\'ve Made a Huge Moustak'});
db.teams.insert({team:'GRAN', owner:'Josh Granata', fullName:'Ron Paul Revolution'});
db.teams.insert({team:'SHAW', owner:'Ian Tasso', fullName:'Kershawshank Redemption'});
db.teams.insert({team:'JEFF', owner:'Darren Grove', fullName:'Jeff Berkasaurus Rex'});
db.teams.insert({team:'GLRY', owner:'Jeff Berk', fullName:'The Glorioles'});
db.teams.insert({team:'SIDO', owner:'David Sidorov', fullName:'Crown Heights Riots'});
db.teams.insert({team:'DBAG', owner:'Jacob Gerber/Matt Shapiro', fullName:'The Baghdad Daddy Bags'});
db.teams.insert({team:'CHOB', owner:'Brian McGlade', fullName:'Chobani Wheredmycargo'});
db.teams.insert({team:'HIV+', owner:'Michael Pollack', fullName:'Arthur Ashe'});
db.teams.insert({team:'PUIG', owner:'Antoine Gobin', fullName:'Macho Macho Manny'});
db.teams.insert({team:'MAD', owner:'Michael Davey', fullName:'Uncanny Contenders'});
db.teams.insert({team:'LAZ', owner:'Brendan Lazarus', fullName:'Las Vegas Isotopes'});
