db.teams.remove();
db.teams.insert({team:'GOB', owner:'Ari Golub', fullName:'I\'ve Made a Huge Moustak', history: [{year:2014, keeper_total:32}]});
db.teams.insert({team:'GRAN', owner:'Josh Granata', fullName:'Ron Paul Revolution', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'SHAW', owner:'Ian Tasso', fullName:'Kershawshank Redemption', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'JEFF', owner:'Darren Grove', fullName:'Jeff Berkasaurus Rex', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'GLRY', owner:'Jeff Berk', fullName:'The Glorioles', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'SIDO', owner:'David Sidorov', fullName:'Crown Heights Riots', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'DBAG', owner:'Jacob Gerber/Matt Shapiro', fullName:'The Baghdad Daddy Bags', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'CHOB', owner:'Brian McGlade', fullName:'Chobani Wheredmycargo', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'HIV+', owner:'Michael Pollack', fullName:'Arthur Ashe', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'PUIG', owner:'Antoine Gobin', fullName:'Macho Macho Manny', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'MAD', owner:'Michael Davey', fullName:'Uncanny Contenders', history: [{year:2014, keeper_total:0}]});
db.teams.insert({team:'LAZ', owner:'Brendan Lazarus', fullName:'Las Vegas Isotopes', history: [{year:2014, keeper_total:0}]});
